### ISSUE TITLE
Add support for an admin console

### ISSUE THREAD

**Issue by signebedi** [libreForms/libreForms-flask#28]
Create an admin portal to view and edit all other users; in the future, restrict this to those of group:admins.

**Comment by signebedi** [comment]
Some features that the admin portal should provide:

- Database externalization
- OAuth Authentication
- SMTP Configuration
- File System Configuration
- User and Group/Role Configuration
- Log Access

**Comment by janoskabedis** [comment]
You can edit .env files programmatically, see https://stackoverflow.com/a/63837452.

Therefore, might be worth pivoting away from config_override.py in favor of a .env.

Or, use both but have the .env take precedence.

**Comment by signebedi** [comment]
You can edit .env files programmatically, see https://stackoverflow.com/a/63837452.

Therefore, might be worth pivoting away from config_override.py in favor of a .env.

Or, use both but have the .env take precedence.

**Comment by signebedi** [comment]
Okay, we've taken the significant first step in defining an admin console for the application. We've built a home view, added some templates, and introduced the side- and top-bar menu logic needed to scale up the number of admin views we want to add. As this is a foundational issue, closing for now and will address next steps in other issues.
