### ISSUE TITLE
[mongo] add support for backing up mongo data

### ISSUE THREAD

**Issue by signebedi** [libreForms/libreForms-flask#470]
It might be worth thinking through backups of mongo data into maybe text archives, zip archives, or something else... I am not sure what the best practice is here but will do some research.

**Comment by janoskabedis** [comment]
[mongo] add celerybeat mongobackup feature with app config and frequency
Currently, we write mongo backups to their own backup db... should we write to file instead? For example, https://dba.stackexchange.com/a/200432. This could be a daily, compressed backup with weekly and monthly retention schedules? This might be overengineering but could be useful to add some, if not all, the functionality.
